# Cosmos Discord Faucet configuration

verbose        = "yes"
gaia_home_folder = "~/.gaia"
transactions_log = "transactions.csv"

[cosmos]
prefix         = "cosmos"
denomination   = "uatom"

[chains]
    [chains.test]
    node_url = "https://rpc.cosmos-chain.com:443"
    chain_id = "test-1"
    faucet_address = ""
    block_explorer_tx = ""
    daily_cap = "250000000"
    amount_to_send = "1000"
    tx_fees = "100"
    description = "A test chain"
    website = ""

[discord]
bot_token = ""
# comma separated list of channels
channels_to_listen = ""
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout  = "86400"